// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum CameraProjection
{
    /// <summary>
    /// Perspective projection
    /// </summary>
    CAMERA_PERSPECTIVE = 0,
    /// <summary>
    /// Orthographic projection
    /// </summary>
    CAMERA_ORTHOGRAPHIC,
}