// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum CodeLang
{
    /// <summary>
    /// Undefined code language, text is plain text
    /// </summary>
    RRES_CODE_LANG_UNDEFINED = 0,
    /// <summary>
    /// Text contains C code
    /// </summary>
    RRES_CODE_LANG_C,
    /// <summary>
    /// Text contains C++ code
    /// </summary>
    RRES_CODE_LANG_CPP,
    /// <summary>
    /// Text contains C# code
    /// </summary>
    RRES_CODE_LANG_CS,
    /// <summary>
    /// Text contains Lua code
    /// </summary>
    RRES_CODE_LANG_LUA,
    /// <summary>
    /// Text contains JavaScript code
    /// </summary>
    RRES_CODE_LANG_JS,
    /// <summary>
    /// Text contains Python code
    /// </summary>
    RRES_CODE_LANG_PYTHON,
    /// <summary>
    /// Text contains Rust code
    /// </summary>
    RRES_CODE_LANG_RUST,
    /// <summary>
    /// Text contains Zig code
    /// </summary>
    RRES_CODE_LANG_ZIG,
    /// <summary>
    /// Text contains Odin code
    /// </summary>
    RRES_CODE_LANG_ODIN,
    /// <summary>
    /// Text contains Jai code
    /// </summary>
    RRES_CODE_LANG_JAI,
    /// <summary>
    /// Text contains GDScript (Godot) code
    /// </summary>
    RRES_CODE_LANG_GDSCRIPT,
    /// <summary>
    /// Text contains GLSL shader code
    /// </summary>
    RRES_CODE_LANG_GLSL,
}