// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum CompressionType
{
    /// <summary>
    /// No data compression
    /// </summary>
    RRES_COMP_NONE = 0,
    /// <summary>
    /// RLE compression
    /// </summary>
    RRES_COMP_RLE = 1,
    /// <summary>
    /// DEFLATE compression
    /// </summary>
    RRES_COMP_DEFLATE = 10,
    /// <summary>
    /// LZ4 compression
    /// </summary>
    RRES_COMP_LZ4 = 20,
    /// <summary>
    /// LZMA2 compression
    /// </summary>
    RRES_COMP_LZMA2 = 30,
    /// <summary>
    /// QOI compression, useful for RGB(A) image data
    /// </summary>
    RRES_COMP_QOI = 40,
}