// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum EncryptionType
{
    /// <summary>
    /// No data encryption
    /// </summary>
    RRES_CIPHER_NONE = 0,
    /// <summary>
    /// XOR encryption, generic using 128bit key in blocks
    /// </summary>
    RRES_CIPHER_XOR = 1,
    /// <summary>
    /// DES encryption
    /// </summary>
    RRES_CIPHER_DES = 10,
    /// <summary>
    /// Triple DES encryption
    /// </summary>
    RRES_CIPHER_TDES = 11,
    /// <summary>
    /// IDEA encryption
    /// </summary>
    RRES_CIPHER_IDEA = 20,
    /// <summary>
    /// AES (128bit or 256bit) encryption
    /// </summary>
    RRES_CIPHER_AES = 30,
    /// <summary>
    /// AES Galois/Counter Mode (Galois Message Authentification Code - GMAC)
    /// </summary>
    RRES_CIPHER_AES_GCM = 31,
    /// <summary>
    /// XTEA encryption
    /// </summary>
    RRES_CIPHER_XTEA = 40,
    /// <summary>
    /// BLOWFISH encryption
    /// </summary>
    RRES_CIPHER_BLOWFISH = 50,
    /// <summary>
    /// RSA asymmetric encryption
    /// </summary>
    RRES_CIPHER_RSA = 60,
    /// <summary>
    /// SALSA20 encryption
    /// </summary>
    RRES_CIPHER_SALSA20 = 70,
    /// <summary>
    /// CHACHA20 encryption
    /// </summary>
    RRES_CIPHER_CHACHA20 = 71,
    /// <summary>
    /// XCHACHA20 encryption
    /// </summary>
    RRES_CIPHER_XCHACHA20 = 72,
    /// <summary>
    /// XCHACHA20 with POLY1305 for message authentification (MAC)
    /// </summary>
    RRES_CIPHER_XCHACHA20_POLY1305 = 73,
}