// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum ErrorType
{
    /// <summary>
    /// rres file loaded/saved successfully
    /// </summary>
    RRES_SUCCESS = 0,
    /// <summary>
    /// rres file can not be opened (spelling issues, file actually does not exist...)
    /// </summary>
    RRES_ERROR_FILE_NOT_FOUND,
    /// <summary>
    /// rres file format not a supported (wrong header, wrong identifier)
    /// </summary>
    RRES_ERROR_FILE_FORMAT,
    /// <summary>
    /// Memory could not be allocated for operation.
    /// </summary>
    RRES_ERROR_MEMORY_ALLOC,
}