// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum FontStyle
{
    /// <summary>
    /// Undefined font style
    /// </summary>
    RRES_FONT_STYLE_UNDEFINED = 0,
    /// <summary>
    /// Regular font style
    /// </summary>
    RRES_FONT_STYLE_REGULAR,
    /// <summary>
    /// Bold font style
    /// </summary>
    RRES_FONT_STYLE_BOLD,
    /// <summary>
    /// Italic font style
    /// </summary>
    RRES_FONT_STYLE_ITALIC,
}