// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GamepadButton
{
    /// <summary>
    /// Unknown button, just for error checking
    /// </summary>
    GAMEPAD_BUTTON_UNKNOWN = 0,
    /// <summary>
    /// Gamepad left DPAD up button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_FACE_UP,
    /// <summary>
    /// Gamepad left DPAD right button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_FACE_RIGHT,
    /// <summary>
    /// Gamepad left DPAD down button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_FACE_DOWN,
    /// <summary>
    /// Gamepad left DPAD left button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_FACE_LEFT,
    /// <summary>
    /// Gamepad right button up (i.e. PS3: Triangle, Xbox: Y)
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_FACE_UP,
    /// <summary>
    /// Gamepad right button right (i.e. PS3: Circle, Xbox: B)
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
    /// <summary>
    /// Gamepad right button down (i.e. PS3: Cross, Xbox: A)
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
    /// <summary>
    /// Gamepad right button left (i.e. PS3: Square, Xbox: X)
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
    /// <summary>
    /// Gamepad top/back trigger left (first), it could be a trailing button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_TRIGGER_1,
    /// <summary>
    /// Gamepad top/back trigger left (second), it could be a trailing button
    /// </summary>
    GAMEPAD_BUTTON_LEFT_TRIGGER_2,
    /// <summary>
    /// Gamepad top/back trigger right (first), it could be a trailing button
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_TRIGGER_1,
    /// <summary>
    /// Gamepad top/back trigger right (second), it could be a trailing button
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_TRIGGER_2,
    /// <summary>
    /// Gamepad center buttons, left one (i.e. PS3: Select)
    /// </summary>
    GAMEPAD_BUTTON_MIDDLE_LEFT,
    /// <summary>
    /// Gamepad center buttons, middle one (i.e. PS3: PS, Xbox: XBOX)
    /// </summary>
    GAMEPAD_BUTTON_MIDDLE,
    /// <summary>
    /// Gamepad center buttons, right one (i.e. PS3: Start)
    /// </summary>
    GAMEPAD_BUTTON_MIDDLE_RIGHT,
    /// <summary>
    /// Gamepad joystick pressed button left
    /// </summary>
    GAMEPAD_BUTTON_LEFT_THUMB,
    /// <summary>
    /// Gamepad joystick pressed button right
    /// </summary>
    GAMEPAD_BUTTON_RIGHT_THUMB,
}