// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum Gesture
{
    /// <summary>
    /// No gesture
    /// </summary>
    GESTURE_NONE = 0,
    /// <summary>
    /// Tap gesture
    /// </summary>
    GESTURE_TAP = 1,
    /// <summary>
    /// Double tap gesture
    /// </summary>
    GESTURE_DOUBLETAP = 2,
    /// <summary>
    /// Hold gesture
    /// </summary>
    GESTURE_HOLD = 4,
    /// <summary>
    /// Drag gesture
    /// </summary>
    GESTURE_DRAG = 8,
    /// <summary>
    /// Swipe right gesture
    /// </summary>
    GESTURE_SWIPE_RIGHT = 16,
    /// <summary>
    /// Swipe left gesture
    /// </summary>
    GESTURE_SWIPE_LEFT = 32,
    /// <summary>
    /// Swipe up gesture
    /// </summary>
    GESTURE_SWIPE_UP = 64,
    /// <summary>
    /// Swipe down gesture
    /// </summary>
    GESTURE_SWIPE_DOWN = 128,
    /// <summary>
    /// Pinch in gesture
    /// </summary>
    GESTURE_PINCH_IN = 256,
    /// <summary>
    /// Pinch out gesture
    /// </summary>
    GESTURE_PINCH_OUT = 512,
}