// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiCheckBoxProperty
{
    /// <summary>
    /// CheckBox internal check padding
    /// </summary>
    CHECK_PADDING = 16,
}