// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiControl
{
    /// <summary>
    /// Default -&gt; populates to all controls when set
    /// </summary>
    DEFAULT = 0,
    /// <summary>
    /// Used also for: LABELBUTTON
    /// </summary>
    LABEL = 1,
    BUTTON = 2,
    /// <summary>
    /// Used also for: TOGGLEGROUP
    /// </summary>
    TOGGLE = 3,
    /// <summary>
    /// Used also for: SLIDERBAR, TOGGLESLIDER
    /// </summary>
    SLIDER = 4,
    PROGRESSBAR = 5,
    CHECKBOX = 6,
    COMBOBOX = 7,
    DROPDOWNBOX = 8,
    /// <summary>
    /// Used also for: TEXTBOXMULTI
    /// </summary>
    TEXTBOX = 9,
    VALUEBOX = 10,
    TABBAR = 11,
    LISTVIEW = 12,
    COLORPICKER = 13,
    SCROLLBAR = 14,
    STATUSBAR = 15,
}