// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiComboBoxProperty
{
    /// <summary>
    /// ComboBox right button width
    /// </summary>
    COMBO_BUTTON_WIDTH = 16,
    /// <summary>
    /// ComboBox button separation
    /// </summary>
    COMBO_BUTTON_SPACING,
}