// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiDefaultProperty
{
    /// <summary>
    /// Text size (glyphs max height)
    /// </summary>
    TEXT_SIZE = 16,
    /// <summary>
    /// Text spacing between glyphs
    /// </summary>
    TEXT_SPACING,
    /// <summary>
    /// Line control color
    /// </summary>
    LINE_COLOR,
    /// <summary>
    /// Background color
    /// </summary>
    BACKGROUND_COLOR,
    /// <summary>
    /// Text spacing between lines
    /// </summary>
    TEXT_LINE_SPACING,
    /// <summary>
    /// Text vertical alignment inside text bounds (after border and padding)
    /// </summary>
    TEXT_ALIGNMENT_VERTICAL,
    /// <summary>
    /// Text wrap-mode inside text bounds
    /// </summary>
    TEXT_WRAP_MODE,
}