// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiProgressBarProperty
{
    /// <summary>
    /// ProgressBar internal padding
    /// </summary>
    PROGRESS_PADDING = 16,
}