// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiProgressBarProperty
{
    /// <summary>
    /// ProgressBar internal padding
    /// </summary>
    PROGRESS_PADDING = 16,
    /// <summary>
    /// ProgressBar increment side: 0-left-&gt;right, 1-right-left
    /// </summary>
    PROGRESS_SIDE,
}