// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiSliderProperty
{
    /// <summary>
    /// Slider size of internal bar
    /// </summary>
    SLIDER_WIDTH = 16,
    /// <summary>
    /// Slider/SliderBar internal bar padding
    /// </summary>
    SLIDER_PADDING,
}