// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiTextBoxProperty
{
    /// <summary>
    /// TextBox in read-only mode: 0-text editable, 1-text no-editable
    /// </summary>
    TEXT_READONLY = 16,
}