// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiTabBarProperty
{
    /// <summary>
    /// TabBar tab items width
    /// </summary>
    TAB_ITEMS_WIDTH = 16,
    /// <summary>
    /// TabBar tab close button: 0-Not shown, 1-Shown
    /// </summary>
    TAB_CLOSE_BUTTON,
    /// <summary>
    /// TabBar tabs side: 0-Bottom, 1-Top
    /// </summary>
    TAB_LINE_SIDE,
}