// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiTextBoxProperty
{
    /// <summary>
    /// TextBox in read-only mode: 0-Text editable, 1-Text read-only
    /// </summary>
    TEXT_READONLY = 16,
}