// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiToggleProperty
{
    /// <summary>
    /// ToggleGroup separation between toggles
    /// </summary>
    GROUP_PADDING = 16,
}