// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum GuiValueBoxProperty
{
    /// <summary>
    /// Spinner left/right buttons width
    /// </summary>
    SPINNER_BUTTON_WIDTH = 16,
    /// <summary>
    /// Spinner buttons separation
    /// </summary>
    SPINNER_BUTTON_SPACING,
}