// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum MouseButton
{
    /// <summary>
    /// Mouse button left
    /// </summary>
    MOUSE_BUTTON_LEFT = 0,
    /// <summary>
    /// Mouse button right
    /// </summary>
    MOUSE_BUTTON_RIGHT = 1,
    /// <summary>
    /// Mouse button middle (pressed wheel)
    /// </summary>
    MOUSE_BUTTON_MIDDLE = 2,
    /// <summary>
    /// Mouse button side (advanced mouse device)
    /// </summary>
    MOUSE_BUTTON_SIDE = 3,
    /// <summary>
    /// Mouse button extra (advanced mouse device)
    /// </summary>
    MOUSE_BUTTON_EXTRA = 4,
    /// <summary>
    /// Mouse button forward (advanced mouse device)
    /// </summary>
    MOUSE_BUTTON_FORWARD = 5,
    /// <summary>
    /// Mouse button back (advanced mouse device)
    /// </summary>
    MOUSE_BUTTON_BACK = 6,
}