// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum NPatchLayout
{
    /// <summary>
    /// Npatch layout: 3x3 tiles
    /// </summary>
    NPATCH_NINE_PATCH = 0,
    /// <summary>
    /// Npatch layout: 1x3 tiles
    /// </summary>
    NPATCH_THREE_PATCH_VERTICAL,
    /// <summary>
    /// Npatch layout: 3x1 tiles
    /// </summary>
    NPATCH_THREE_PATCH_HORIZONTAL,
}