// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum ResourceDataType
{
    /// <summary>
    /// FourCC: NULL - Reserved for empty chunks, no props/data
    /// </summary>
    RRES_DATA_NULL = 0,
    /// <summary>
    /// FourCC: RAWD - Raw file data, 4 properties
    /// </summary>
    RRES_DATA_RAW = 1,
    /// <summary>
    /// FourCC: TEXT - Text file data, 4 properties
    /// </summary>
    RRES_DATA_TEXT = 2,
    /// <summary>
    /// FourCC: IMGE - Image file data, 4 properties
    /// </summary>
    RRES_DATA_IMAGE = 3,
    /// <summary>
    /// FourCC: WAVE - Audio file data, 4 properties
    /// </summary>
    RRES_DATA_WAVE = 4,
    /// <summary>
    /// FourCC: VRTX - Vertex file data, 4 properties
    /// </summary>
    RRES_DATA_VERTEX = 5,
    /// <summary>
    /// FourCC: FNTG - Font glyphs info data, 4 properties
    /// </summary>
    RRES_DATA_FONT_GLYPHS = 6,
    /// <summary>
    /// FourCC: LINK - External linked file, 1 property
    /// </summary>
    RRES_DATA_LINK = 99,
    /// <summary>
    /// FourCC: CDIR - Central directory for input files
    /// </summary>
    RRES_DATA_DIRECTORY = 100,
}