// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum TextEncoding
{
    /// <summary>
    /// Not defined, usually UTF-8
    /// </summary>
    RRES_TEXT_ENCODING_UNDEFINED = 0,
    /// <summary>
    /// UTF-8 text encoding
    /// </summary>
    RRES_TEXT_ENCODING_UTF8 = 1,
    /// <summary>
    /// UTF-8 text encoding with Byte-Order-Mark
    /// </summary>
    RRES_TEXT_ENCODING_UTF8_BOM = 2,
    /// <summary>
    /// UTF-16 Little Endian text encoding
    /// </summary>
    RRES_TEXT_ENCODING_UTF16_LE = 10,
    /// <summary>
    /// UTF-16 Big Endian text encoding
    /// </summary>
    RRES_TEXT_ENCODING_UTF16_BE = 11,
}