// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum VertexFormat
{
    /// <summary>
    /// 8 bit unsigned integer data
    /// </summary>
    RRES_VERTEX_FORMAT_UBYTE = 0,
    /// <summary>
    /// 8 bit signed integer data
    /// </summary>
    RRES_VERTEX_FORMAT_BYTE,
    /// <summary>
    /// 16 bit unsigned integer data
    /// </summary>
    RRES_VERTEX_FORMAT_USHORT,
    /// <summary>
    /// 16 bit signed integer data
    /// </summary>
    RRES_VERTEX_FORMAT_SHORT,
    /// <summary>
    /// 32 bit unsigned integer data
    /// </summary>
    RRES_VERTEX_FORMAT_UINT,
    /// <summary>
    /// 32 bit integer data
    /// </summary>
    RRES_VERTEX_FORMAT_INT,
    /// <summary>
    /// 16 bit float data
    /// </summary>
    RRES_VERTEX_FORMAT_HFLOAT,
    /// <summary>
    /// 32 bit float data
    /// </summary>
    RRES_VERTEX_FORMAT_FLOAT,
}