// This file was generated by Bindgen, do not edit it manually.
namespace RaylibNET;

public enum VertexAttribute
{
    /// <summary>
    /// Vertex position attribute: [x, y, z]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_POSITION = 0,
    /// <summary>
    /// Vertex texture coordinates attribute: [u, v]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_TEXCOORD1 = 10,
    /// <summary>
    /// Vertex texture coordinates attribute: [u, v]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_TEXCOORD2 = 11,
    /// <summary>
    /// Vertex texture coordinates attribute: [u, v]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_TEXCOORD3 = 12,
    /// <summary>
    /// Vertex texture coordinates attribute: [u, v]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_TEXCOORD4 = 13,
    /// <summary>
    /// Vertex normal attribute: [x, y, z]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_NORMAL = 20,
    /// <summary>
    /// Vertex tangent attribute: [x, y, z, w]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_TANGENT = 30,
    /// <summary>
    /// Vertex color attribute: [r, g, b, a]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_COLOR = 40,
    /// <summary>
    /// Vertex index attribute: [i]
    /// </summary>
    RRES_VERTEX_ATTRIBUTE_INDEX = 100,
}