// This file was generated by Bindgen, do not edit it manually.
using Xunit;
using Bindgen.Test;

namespace RaylibNET.Test;

public class RresTest
{
    private unsafe void CheckType<T>() where T : unmanaged
    {
        Assert.True(BlittableHelper.IsBlittable<T>());
    }

    [Fact]
    public void CheckTypes()
    {
        CheckType<ResourceDataType>();
        CheckType<CompressionType>();
        CheckType<EncryptionType>();
        CheckType<ErrorType>();
        CheckType<TextEncoding>();
        CheckType<CodeLang>();
        CheckType<PixelFormat>();
        CheckType<VertexAttribute>();
        CheckType<VertexFormat>();
        CheckType<FontStyle>();
        CheckType<FileHeader>();
        CheckType<ResourceChunkInfo>();
        CheckType<ResourceChunkData>();
        CheckType<ResourceChunk>();
        CheckType<ResourceMulti>();
        CheckType<DirEntry>();
        CheckType<CentralDir>();
        CheckType<FontGlyphInfo>();
    }
}
