// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

public static unsafe partial class Rres
{
    public const string LIBRARY = "raylib";

    public const int RRES_MAX_FILENAME_SIZE = 1024;

    /// <summary>
    /// Load one resource chunk for provided id
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial ResourceChunk rresLoadResourceChunk(string fileName, int rresId);

    /// <summary>
    /// Unload resource chunk from memory
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void rresUnloadResourceChunk(ResourceChunk chunk);

    /// <summary>
    /// Load resource for provided id (multiple resource chunks)
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial ResourceMulti rresLoadResourceMulti(string fileName, int rresId);

    /// <summary>
    /// Unload resource from memory (multiple resource chunks)
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void rresUnloadResourceMulti(ResourceMulti multi);

    /// <summary>
    /// Load resource chunk info for provided id
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial ResourceChunkInfo rresLoadResourceChunkInfo(string fileName, int rresId);

    /// <summary>
    /// Load all resource chunks info
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static unsafe partial ResourceChunkInfo* rresLoadResourceChunkInfoAll(string fileName, uint* chunkCount);

    /// <summary>
    /// Load central directory resource chunk from file
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial CentralDir rresLoadCentralDirectory(string fileName);

    /// <summary>
    /// Unload central directory resource chunk
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void rresUnloadCentralDirectory(CentralDir dir);

    /// <summary>
    /// Get rresResourceDataType from FourCC code
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static unsafe partial uint rresGetDataType(byte* fourCC);

    /// <summary>
    /// Get resource id for a provided filename
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial int rresGetResourceId(CentralDir dir, string fileName);

    /// <summary>
    /// Compute CRC32 for provided data
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static unsafe partial uint rresComputeCRC32(byte* data, int len);

    /// <summary>
    /// Set password to be used on data decryption
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial void rresSetCipherPassword(string pass);

    /// <summary>
    /// Get password to be used on data decryption
    /// </summary>
    [LibraryImport(LIBRARY, StringMarshalling = StringMarshalling.Utf8)]
    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
    public static partial string rresGetCipherPassword();
}
