// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct AutomationEventList
{
    /// <summary>
    /// Events max entries (MAX_AUTOMATION_EVENTS)
    /// </summary>
    public uint Capacity;
    /// <summary>
    /// Events entries count
    /// </summary>
    public uint Count;
    /// <summary>
    /// Events entries
    /// </summary>
    public unsafe AutomationEvent* Events;

    public unsafe AutomationEventList(uint capacity, uint count, AutomationEvent* events)
    {
        this.Capacity = capacity;
        this.Count = count;
        this.Events = events;
    }
}