// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct Camera2D
{
    /// <summary>
    /// Camera offset (screen space offset from window origin)
    /// </summary>
    public Vector2 Offset;
    /// <summary>
    /// Camera target (world space target point that is mapped to screen space offset)
    /// </summary>
    public Vector2 Target;
    /// <summary>
    /// Camera rotation in degrees (pivots around target)
    /// </summary>
    public float Rotation;
    /// <summary>
    /// Camera zoom (scaling around target), must not be set to 0, set to 1.0f for no scale
    /// </summary>
    public float Zoom;

    public Camera2D(Vector2 offset, Vector2 target, float rotation, float zoom)
    {
        this.Offset = offset;
        this.Target = target;
        this.Rotation = rotation;
        this.Zoom = zoom;
    }
}