// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct CentralDir
{
    /// <summary>
    /// Central directory entries count
    /// </summary>
    public uint Count;
    /// <summary>
    /// Central directory entries
    /// </summary>
    public unsafe DirEntry* Entries;

    public unsafe CentralDir(uint count, DirEntry* entries)
    {
        this.Count = count;
        this.Entries = entries;
    }
}