// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct DirEntry
{
    /// <summary>
    /// Resource id
    /// </summary>
    public uint Id;
    /// <summary>
    /// Resource global offset in file
    /// </summary>
    public uint Offset;
    /// <summary>
    /// reserved
    /// </summary>
    public uint Reserved;
    /// <summary>
    /// Resource fileName size (NULL terminator and 4-byte alignment padding considered)
    /// </summary>
    public uint FileNameSize;
    /// <summary>
    /// Resource original fileName (NULL terminated and padded to 4-byte alignment)
    /// </summary>
    public unsafe fixed sbyte FileName[1024];
}