// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct FileHeader
{
    /// <summary>
    /// File identifier: rres
    /// </summary>
    public unsafe fixed byte Id[4];
    /// <summary>
    /// File version: 100 for version 1.0
    /// </summary>
    public ushort Version;
    /// <summary>
    /// Number of resource chunks in the file (MAX: 65535)
    /// </summary>
    public ushort ChunkCount;
    /// <summary>
    /// Central Directory offset in file (0 if not available)
    /// </summary>
    public uint CdOffset;
    /// <summary>
    /// &lt;reserved&gt;
    /// </summary>
    public uint Reserved;
}