// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct FontGlyphInfo
{
    /// <summary>
    /// Glyph rectangle in the atlas image
    /// </summary>
    public int X;
    /// <summary>
    /// Glyph rectangle in the atlas image
    /// </summary>
    public int Y;
    /// <summary>
    /// Glyph rectangle in the atlas image
    /// </summary>
    public int Width;
    /// <summary>
    /// Glyph rectangle in the atlas image
    /// </summary>
    public int Height;
    /// <summary>
    /// Glyph codepoint value
    /// </summary>
    public int Value;
    /// <summary>
    /// Glyph drawing offset (from base line)
    /// </summary>
    public int OffsetX;
    /// <summary>
    /// Glyph drawing offset (from base line)
    /// </summary>
    public int OffsetY;
    /// <summary>
    /// Glyph advance X for next character
    /// </summary>
    public int AdvanceX;

    public FontGlyphInfo(int x, int y, int width, int height, int value, int offsetX, int offsetY, int advanceX)
    {
        this.X = x;
        this.Y = y;
        this.Width = width;
        this.Height = height;
        this.Value = value;
        this.OffsetX = offsetX;
        this.OffsetY = offsetY;
        this.AdvanceX = advanceX;
    }
}