// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct MaterialMap
{
    /// <summary>
    /// Material map texture
    /// </summary>
    public Texture Texture;
    /// <summary>
    /// Material map color
    /// </summary>
    public Color Color;
    /// <summary>
    /// Material map value
    /// </summary>
    public float Value;

    public MaterialMap(Texture texture, Color color, float value)
    {
        this.Texture = texture;
        this.Color = color;
        this.Value = value;
    }
}