// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ModelSkeleton
{
    /// <summary>
    /// Number of bones
    /// </summary>
    public int BoneCount;
    /// <summary>
    /// Bones information (skeleton)
    /// </summary>
    public unsafe BoneInfo* Bones;
    /// <summary>
    /// Bones base transformation (Transform[])
    /// </summary>
    public unsafe Transform* BindPose;

    public unsafe ModelSkeleton(int boneCount, BoneInfo* bones, Transform* bindPose)
    {
        this.BoneCount = boneCount;
        this.Bones = bones;
        this.BindPose = bindPose;
    }
}