// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct Model
{
    /// <summary>
    /// Local transform matrix
    /// </summary>
    public Matrix4x4 Transform;
    /// <summary>
    /// Number of meshes
    /// </summary>
    public int MeshCount;
    /// <summary>
    /// Number of materials
    /// </summary>
    public int MaterialCount;
    /// <summary>
    /// Meshes array
    /// </summary>
    public unsafe Mesh* Meshes;
    /// <summary>
    /// Materials array
    /// </summary>
    public unsafe Material* Materials;
    /// <summary>
    /// Mesh material number
    /// </summary>
    public unsafe int* MeshMaterial;
    /// <summary>
    /// Skeleton for animation
    /// </summary>
    public ModelSkeleton Skeleton;
    /// <summary>
    /// Current animation pose (Transform[])
    /// </summary>
    public unsafe Transform* CurrentPose;
    /// <summary>
    /// Bones animated transformation matrices
    /// </summary>
    public unsafe Matrix4x4* BoneMatrices;

    public unsafe Model(Matrix4x4 transform, int meshCount, int materialCount, Mesh* meshes, Material* materials, int* meshMaterial, ModelSkeleton skeleton, Transform* currentPose, Matrix4x4* boneMatrices)
    {
        this.Transform = transform;
        this.MeshCount = meshCount;
        this.MaterialCount = materialCount;
        this.Meshes = meshes;
        this.Materials = materials;
        this.MeshMaterial = meshMaterial;
        this.Skeleton = skeleton;
        this.CurrentPose = currentPose;
        this.BoneMatrices = boneMatrices;
    }
}