// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ModelAnimation
{
    /// <summary>
    /// Animation name
    /// </summary>
    public unsafe fixed sbyte Name[32];
    /// <summary>
    /// Number of bones (per pose)
    /// </summary>
    public int BoneCount;
    /// <summary>
    /// Number of animation key frames
    /// </summary>
    public int KeyframeCount;
    /// <summary>
    /// Animation sequence keyframe poses [keyframe][pose]
    /// </summary>
    public unsafe Transform** KeyframePoses;
}