// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ResourceChunkInfo
{
    /// <summary>
    /// Resource chunk type (FourCC)
    /// </summary>
    public unsafe fixed byte Type[4];
    /// <summary>
    /// Resource chunk identifier (generated from filename CRC32 hash)
    /// </summary>
    public uint Id;
    /// <summary>
    /// Data compression algorithm
    /// </summary>
    public byte CompType;
    /// <summary>
    /// Data encription algorithm
    /// </summary>
    public byte CipherType;
    /// <summary>
    /// Data flags (if required)
    /// </summary>
    public ushort Flags;
    /// <summary>
    /// Data chunk size (compressed/encrypted + custom data appended)
    /// </summary>
    public uint PackedSize;
    /// <summary>
    /// Data base size (uncompressed/unencrypted)
    /// </summary>
    public uint BaseSize;
    /// <summary>
    /// Next resource chunk global offset (if resource has multiple chunks)
    /// </summary>
    public uint NextOffset;
    /// <summary>
    /// <reserved>
    /// </summary>
    public uint Reserved;
    /// <summary>
    /// Data chunk CRC32 (propCount + props[] + data)
    /// </summary>
    public uint Crc32;
}