// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ResourceChunkData
{
    /// <summary>
    /// Resource chunk properties count
    /// </summary>
    public uint PropCount;
    /// <summary>
    /// Resource chunk properties
    /// </summary>
    public unsafe uint* Props;
    /// <summary>
    /// Resource chunk raw data
    /// </summary>
    public unsafe void* Raw;

    public unsafe ResourceChunkData(uint propCount, uint* props, void* raw)
    {
        this.PropCount = propCount;
        this.Props = props;
        this.Raw = raw;
    }
}