// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ResourceChunk
{
    /// <summary>
    /// Resource chunk info
    /// </summary>
    public ResourceChunkInfo Info;
    /// <summary>
    /// Resource chunk packed data, contains propCount, props[] and raw data
    /// </summary>
    public ResourceChunkData Data;

    public ResourceChunk(ResourceChunkInfo info, ResourceChunkData data)
    {
        this.Info = info;
        this.Data = data;
    }
}