// This file was generated by Bindgen, do not edit it manually.
using System.Runtime.InteropServices;
using Bindgen.Interop;
using System.Numerics;

namespace RaylibNET;

[StructLayout(LayoutKind.Sequential)]
public partial struct ResourceMulti
{
    /// <summary>
    /// Resource chunks count
    /// </summary>
    public uint Count;
    /// <summary>
    /// Resource chunks
    /// </summary>
    public unsafe ResourceChunk* Chunks;

    public unsafe ResourceMulti(uint count, ResourceChunk* chunks)
    {
        this.Count = count;
        this.Chunks = chunks;
    }
}