name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-bindings:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build -c Release src/Raylib.NET.Bindgen

      - name: Push Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          if [ -n "$(git status --porcelain)" ]; then
             git add .
             git commit -m "Update bindings"
             git push
          else
             echo "No changes to commit"
          fi

  natives:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macos-latest
            runtime: osx-x64
          - os: windows-latest
            runtime: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Environment
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install \
              gcc-multilib \
              libasound2-dev \
              libx11-dev \
              libxrandr-dev \
              libxi-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              libxcursor-dev \
              libxinerama-dev \
              libwayland-dev \
              libxkbcommon-dev

      - name: Build Natives
        run: dotnet build -c ${{ matrix.config }} -r ${{ matrix.runtime }}
        working-directory: src/Raylib.NET.Native

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: natives-${{ matrix.config }}-${{ matrix.runtime }}
          path: src/Raylib.NET.Native/bin/${{ matrix.config }}/runtimes/**
          if-no-files-found: error

  prepare-package-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-info.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate Version Info
        id: package-info
        run: |
          echo version=$(git rev-parse --short HEAD) >> $env:GITHUB_OUTPUT

      - name: Print Version Info
        run: |
          echo "Version: ${{ steps.package-info.outputs.version }}"

  build-and-upload:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs:
      - natives
      - prepare-package-info
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download Debug Natives
        uses: actions/download-artifact@v4
        with:
          pattern: natives-Debug-*
          path: src/Raylib.NET.Native/bin/Debug/runtimes/

      - name: Download Release Natives
        uses: actions/download-artifact@v4
        with:
          pattern: natives-Release-*
          path: src/Raylib.NET.Native/bin/Debug/runtimes/

      - name: Create NuGet Debug Packages
        run: dotnet pack -c Debug --output nuget -p:SkipCompileNatives=true -p:VersionSuffix=${{ needs.prepare-package-info.outputs.version }}

      - name: Create NuGet Release Packages
        run: dotnet pack -c Release --output nuget -p:SkipCompileNatives=true -p:VersionSuffix=${{ needs.prepare-package-info.outputs.version }}

      - name: Upload NuGet Packages As Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: nuget/*

      - name: Publish NuGet Packages to GitHub Packages
        run: dotnet nuget push nuget/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
