name: Build
on:
  push:
    branches:
      - master

jobs:
  bindgen-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build -c Release src/Raylib.NET.Bindgen

  natives-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Environment
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install gcc-multilib
          sudo apt-get install \
              libasound2-dev \
              libx11-dev \
              libxrandr-dev \
              libxi-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              libxcursor-dev \
              libxinerama-dev \
              libwayland-dev \
              libxkbcommon-dev

      - name: Build
        run: dotnet build -c Release src/Raylib.NET.Native

  # natives:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #
  #     - name: Setup .NET 8
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 8.0.x
  #
  #     - name: Build
  #       run: dotnet build -c Release
