name: Build
on:
  push:
    branches:
      - master

jobs:
  bindgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build -c Release src/Raylib.NET.Bindgen

  natives:
    strategy:
      matrix:
        distribution: [linux-x64, osx-x64, win-x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Environment
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install gcc-multilib
          sudo apt-get install \
              libasound2-dev \
              libx11-dev \
              libxrandr-dev \
              libxi-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              libxcursor-dev \
              libxinerama-dev \
              libwayland-dev \
              libxkbcommon-dev

      - name: Build Natives
        run: dotnet build -c Release -r {{ matrix.distribution }}
        working-directory: src/Raylib.NET.Native

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: natives-{{ matrix.distribution }}
          path: src/Raylib.NET.Native/bin/Release/native/{{ matrix.distribution }}/*
          if-no-files-found: error

  nuget:
    runs-on: ubuntu-latest
    needs: [bindgen, natives]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download linux-x64 Natives
        uses: actions/download-artifact@v4
        with:
          name: natives-linux-x64
          path: src/Raylib.NET.Native/bin/Release/native/linux-x64

      - name: Download osx-x64 Natives
        uses: actions/download-artifact@v4
        with:
          name: natives-osx-x64
          path: src/Raylib.NET.Native/bin/Release/native/osx-x64

      - name: Download win-x64 Natives
        uses: actions/download-artifact@v4
        with:
          name: natives-win-x64
          path: src/Raylib.NET.Native/bin/Release/native/win-x64

      - name: Create NuGet Package
        run: dotnet pack Raylib.NET -c Release --output nuget

      - name: Upload NuGet Package As Artifact
        uses: actions/upload-artifact@v4
        with:
          path: nuget/*
