name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-bindings:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build -c Release src/Raylib.NET.Bindgen

      - name: Push Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          if [ -n "$(git status --porcelain)" ]; then
             git add .
             git commit -m "Update bindings"
             git push
          else
             echo "No changes to commit"
          fi

  build-and-upload:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    needs:
      - update-bindings
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Generate NuGet Version
        id: package-info
        run: |
          echo "version=dev-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create NuGet Packages
        run: dotnet pack -c Release --output nuget -p:SkipCompileNatives=true -p:VersionSuffix=${{ steps.package-info.outputs.version }}

      - name: Remove Native Packages
        run: rm -rf nuget/Raylib.NET.Native*

      - name: Upload NuGet Packages As Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: nuget/*

      - name: Publish NuGet Packages to GitHub Packages
        run: dotnet nuget push nuget/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
